DATA	SEGMENT
	NUM1	DW	1854H	;W= WORD, B= BYTE, D= DOUBLE			
	NUM2	DW	0012H
	SUM	DW	?
	CARRY	DB	00H
	DIFF	DW	?
	BORROW	DB	00H
	PRODUCT	DD	?
	QUO	DW	?
	REM	DW	?
	DATA	ENDS	
; THIS IS THE BEGINNING OF MY CODE SEGMENT
	CODE	SEGMENT
	ASSUME	CS:CODE, DS:DATA
START:	MOV	AX,	DATA
	MOV	DS,	AX
; THIS PART OF PROG IS FOR ADDITION
	MOV	AX,	NUM1	; AX=NUM1=1854H
	MOV	BX,	NUM2	; BX=NUM2=0012H
	ADD	AX,	BX	; AX=AX+BX
	JNC	L1		; JNC=JUMP IF NO CARRY AND L= LABEL DE RAHE H APAN.
	INC	CARRY		; INC= INCREMENT
L1:	MOV	SUM,	AX
; THIS PART OF PROG IS FOR SUBTRACTION
	MOV	AX,	NUM1
	SUB	AX,	BX	; AX= AX-BX
	JNC	L2
	INC	BORROW
L2:	MOV	DIFF,	AX
;THIS PART OF PROG IS FOR MULTIPLICATION
	MOV 	AX,	NUM1
	MOV	DX,	000H
	MUL	BX		; DX:AX=AX*BX
	LEA	SI,	PRODUCT	; LEA= LOAD EFFECIVE ADDRESS...(it moves the contents of the designated memory location(DX:AX) into the target register) 
	MOV	[SI],	AX
	MOV	[SI]+2,	DX	; LET SI= 1000, 1000 AND 1001 PR AX KA 2BYTE HAI, ISLIYE 1000+2 KIYA.
;THIS PART OF PROG IS FOR DIVISION
	MOV	AX,	NUM1
	MOV	DX,	000H;	; DX:AX= 00001854H
	DIV	BX		; (DX:AX)/BX = QUO=AX, REM=DX
	MOV	QUO,	AX
	MOV	REM,	DX
;DONE..
	INT	3H
	MOV	AX,	4C00H
	INT	21H
	CODE	ENDS
	END	START
